<a href="https://colab.research.google.com/github/MuhammadjonArabov/Python-For-Data-Analytics/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
a = np.array([4, True, True])
print(f"a = {a.all()}")
b = np.array([True, False, True])
print(f"b = {b.all()}")

a = True
b = False


In [ ]:
print(f"any = {a.any()}")
d = np.array([False, 0, False])
print(f"d = {d.any()}")

any = True
d = False


In [ ]:
s = np.array([23, 12, 45, 67, 8])
print(np.take(s, [0, 2]))

[23 45]


In [ ]:
S = np.array([1, 2, 3, 4, 5, 6, 7])
np.put(S, [1, 3], [89, 79])
print(S)

[ 1 89  3 79  5  6  7]


In [ ]:
print(np.diag(s))
b = np.array([[1, 2, 3], [5, 6, 7]])
print(f"b = {np.diag(b)}")
print(f"diagflat = {np.diagflat(b)}")

[[23  0  0  0  0]
 [ 0 89  0  0  0]
 [ 0  0 45  0  0]
 [ 0  0  0 79  0]
 [ 0  0  0  0  8]]
b = [1 6]
diagflat = [[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 5 0 0]
 [0 0 0 0 6 0]
 [0 0 0 0 0 7]]


In [ ]:
idx = np.diag_indices(3)
print(idx)
a = np.zeros((3, 3))
a[idx] = [2, 5, 7]
print(a)

(array([0, 1, 2]), array([0, 1, 2]))
[[2. 0. 0.]
 [0. 5. 0.]
 [0. 0. 7.]]


In [ ]:
a = np.empty([2, 2], dtype=int)
print(f"a = \n {a}")
b = np.empty(2, dtype=int)
print(f"b = \n {b}")

a = 
 [[-4592061934894841856 -4607182418800017408]
 [ 4631310101959933952  4624070917402656768]]
b = 
 [9218868437227405312 9218868437227405312]


In [ ]:
a = np.array([2, 4, 6, 7, 90])
b = np.array([1, 45, 67, 4, 97])
add_ab = a + b
print(f"a + b = {add_ab}")
c = np.add(a, b)
print(f"c = {c}")
d = np.array([1, 2, 3, 4, 1])
total_amount = a + b + d
print(f"total_amount = {total_amount}")
total_amount1 = np.add(a, b, d)
print(f"total_amount1 = {total_amount1}")

a + b = [  3  49  73  11 187]
c = [  3  49  73  11 187]
total_amount = [  4  51  76  15 188]
total_amount1 = [  3  49  73  11 187]


In [ ]:
x = np.array([4, 6, 8, 9])
y = np.array([1, 2, 4, 5])
sub_ab = x - y
print(f"a - b = {sub_ab}")
sub_ab1 = np.subtract(x, y)
print(f"sub_ab1 = {sub_ab1}")

a - b = [3 4 4 4]
sub_ab1 = [3 4 4 4]


In [ ]:
mul_ab = x*y
print(f"x*y = {x*y}")
mul_ab = np.multiply(x, y)
print(f"mul_ab = {mul_ab}")

x*y = [ 4 12 32 45]
mul_ab = [ 4 12 32 45]


In [ ]:
print(f"x/y = {x/y}")
div_ab = np.divide(x, y)
print(f"div_ab = {div_ab}")

x/y = [4.  3.  2.  1.8]
div_ab = [4.  3.  2.  1.8]


In [ ]:
f, g = np.arange(1, 10, 2), np.arange(10, 1, -2)
print(f"f = {f},  g = {g}")

f = [1 3 5 7 9],  g = [10  8  6  4  2]


In [5]:
b = np.array([[[1, 2, 3], [56, 6, 7]],
              [[9, 0, 8], [0, 12, 45]]])

print(b[..., 2])


[[ 3  7]
 [ 8 45]]


In [6]:
g = np.array([
    [2, 3, 4.9],
    [4, 4.3, 1],
    [8, 9.9, 2.2],
    [1, 2.3, 7.8]
])

d = np.array([2, 4, 4])
result = g * d
print(result)

[[ 4.  12.  19.6]
 [ 8.  17.2  4. ]
 [16.  39.6  8.8]
 [ 2.   9.2 31.2]]


In [11]:
v = np.array([1, 2, 3])
w = np.array([9, 1])

print(np.reshape(v, (3, 1)) * w)

X = np.array([[12, 22, 33], [45, 55, 66]])
print(X + v)

print((X.T + w).T)

print(X * 2)

[[ 9  1]
 [18  2]
 [27  3]]
[[13 24 36]
 [46 57 69]]
[[21 31 42]
 [46 56 67]]
[[ 24  44  66]
 [ 90 110 132]]
