<a href="https://colab.research.google.com/github/MuhammadjonArabov/Python-For-Data-Analytics/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
a = np.array([4, True, True])
print(f"a = {a.all()}")
b = np.array([True, False, True])
print(f"b = {b.all()}")

a = True
b = False


In [7]:
print(f"any = {a.any()}")
d = np.array([False, 0, False])
print(f"d = {d.any()}")

any = True
d = False


In [9]:
s = np.array([23, 12, 45, 67, 8])
print(np.take(s, [0, 2]))

[23 45]


In [16]:
S = np.array([1, 2, 3, 4, 5, 6, 7])
np.put(S, [1, 3], [89, 79])
print(S)

[ 1 89  3 79  5  6  7]


In [24]:
print(np.diag(s))
b = np.array([[1, 2, 3], [5, 6, 7]])
print(f"b = {np.diag(b)}")
print(f"diagflat = {np.diagflat(b)}")

[[23  0  0  0  0]
 [ 0 89  0  0  0]
 [ 0  0 45  0  0]
 [ 0  0  0 79  0]
 [ 0  0  0  0  8]]
b = [1 6]
diagflat = [[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 5 0 0]
 [0 0 0 0 6 0]
 [0 0 0 0 0 7]]
